language: node_js

node_js:
  - "8"

branches:
  only:
  - master
  - staging

before_script:
  - npm install -g @angular/cli
  - npm install -g typings
  - typings install firebase --ambient --save

script:
  - ng build --prod --env=prod